Replace install script

diff --git a/dots b/dots
--- a/dots
+++ b/dots
@@ -1,90 +1,120 @@
 #!/bin/sh
-# Back up existing, and install new dotfiles
-# Tested once on OS X 10.8 - good luck ;)
+#
+# Backs up existing files and folders
+# Symlinks whitelisted files and folders into users $HOME
+#
+# inventory of new files and folders
+# backup existing real files and folders
+# delete existing files
+# link files and folders to be linked
+# copy files and folders to be copied
 
 set -e
 set -u
 
-cwd=$(pwd)
-backup_dir="${HOME}/backup/dotfiles"
-target_dir="${HOME}"
-archive=$(date +%Y%m%d)"_dotfiles.tar.gz"
-includes="(^bash*|^git*|^vim*|^bin$)"
+abspath () {
+    case "$1" in
+        /*)
+        printf "%s\n" "$1"
+        ;;
 
-symlink_names() {
-    # dot it if it's in the root directory
-    [[ -f $1 && $(basename $1) = $1 ]] && echo "${target_dir}/.$1" && return 0
-
-    # Do not dot it if it is a directory.
-    # Exemptions made for directories which will not be traversed.
-    case $1 in
-        vim) echo ${target_dir}/.$1 ;;
-        *) find $1 -type f -exec echo "${target_dir}/{}" \; ;;
+        *)
+        printf "%s\n" "$PWD/$1"
+        ;;
     esac
 }
 
-dotsources() {
-    for i in *;do echo "${i}"; done | egrep ${includes}
+sources() {
+    for i in *;do echo "${i}"; done | egrep $1
 }
 
-dotfiles() {
-    for dot_source in $(dotsources); do echo $(symlink_names "${dot_source}"); done
+now=$(date +%Y-%m-%dT%H.%M)
+
+# Script directory
+src_dir=$(dirname $(abspath $0))
+
+# Files to dot and link up in $HOME
+ldfiles="(bash|git|vim)"
+
+# Folders to link content into in the correct places
+linside="(^bin$)"
+
+# Existing files will be backed up here
+backup="$HOME/backup/dotfiles/${now}_dotfiles.tar.gz"
+
+cmd_file="${src_dir}/commands.sh"
+
+# These are the files already mapped up in your $HOME directory
+inventory() {
+	# Give me all real dotfiles in $HOME/ that has a matching file (with or without a dot) in ./
+	# Two find commands because '-type f -o -type d' does not work when you also want to do '-exec'
+	find $HOME -maxdepth 1 -type f -exec echo "{}" \; | egrep "$(sources ${ldfiles})";
+	find $HOME -maxdepth 1 -type d -exec echo "{}" \; | egrep "$(sources ${ldfiles})";
+
+	# Give me all real files inside directories $HOME/{$linside} that has a matching path and filename inside ./{$linside}
+	for dir in $(sources $linside); do find $HOME/$dir -type f 2>/dev/null -exec echo "{}" \; | egrep "$(find $dir -type f -exec echo "$HOME/{}" \;)"; done
 }
 
-existing_dotfiles() {
-    for i in $(dotfiles); do [ -e "${i}" ] && echo "${i}"; done
+run() {
+	# Make sure we're in the source directory
+	cd ${src_dir}
+
+	# Clean up output of $(inventory) so that it is on one line since I don't know how to make that output pretty :'(
+	tbu="" && for file in $(inventory); do tbu="${tbu} ${file}" ; done
+
+	# Ensure backup directory is available and back up - 2>/dev/null to get rid of that pesky 'removing leading '/' message'
+	echo "\$(mkdir -p $(dirname ${backup}))">>${cmd_file}
+	echo "\$(tar -czf ${backup} -C $HOME ${tbu} ${cmd_file} 2>/dev/null || return 0)">>${cmd_file}
+	
+	# Symlink all dotfiles that should be directly in $HOME
+	for df in $(sources $ldfiles); do
+		if [[ -d $HOME/.$df ]]; then
+			echo "\$(rm -rf $HOME/.$df/)">>${cmd_file}
+		else
+			echo "\$(rm -f $HOME/.$df)">>${cmd_file}
+		fi
+		echo "\$(ln -sf $src_dir/$df $HOME/.$df)">>${cmd_file}
+	done
+
+	# Symlink all dotfiles that should be inside a sub-directory of $HOME
+	for sdir in $(sources $linside); do 
+		sdf=$(find $sdir -type f 2>/dev/null -exec echo "{}" \;)
+		for sf in $sdf; do 
+			echo "\$(rm -f $HOME/$sf)">>${cmd_file}
+			echo "\$(ln -sf $src_dir/$sf $HOME/$sf)">>${cmd_file}
+		done
+	done
 }
 
-dotbackup() {
-    mkdir -p ${backup_dir}
+# Start out in script directory
+cd ${src_dir}
 
-    tar -C ${target_dir} -czf ${backup_dir}/${archive} $(existing_dotfiles) || return 0
-}
+# Let's not overwrite an existing file with content.
+if [ -s ${cmd_file} ]
+then 
+	echo 'Halting run of $0 because ${cmd_file} exists and is not empty' 
+	exit 0
+fi
 
-dotdelete() {
-    $(dotbackup)
+# Create command file
+echo "#!/bin/sh">${cmd_file}
+echo "#">>${cmd_file}
+echo "# This file was automatically generated by ${src_dir}/${0}">>${cmd_file}
+echo "# Date: ${now}">>${cmd_file}
+echo "">>${cmd_file}
+echo "set -e">>${cmd_file}
+echo "set -u">>${cmd_file}
+echo "">>${cmd_file}
+$(run)
 
-    for i in $(existing_dotfiles); do rm -rf "${i}"; done
-}
+[[ ($# = 1) && ($1 == '-f') ]] && $(sh ${cmd_file}) && exit 0
 
-ensure_directories() {
-    for potential_dir in $(dotfiles); do
-        dir=$(dirname ${potential_dir})
+printf "\n%s\n\n" "This is the script I plan to run:"
+cat ${cmd_file}
 
-        if [[ ${dir} != "." ]]; then
-            mkdir -p ${dir}
-        fi
-    done
-}
+read -p "Shall I proceed? [y/n]: " yepNope
+[[ $yepNope = 'y' || $yepNope = 'Y' ]] || rm ${cmd_file} && exit 0
 
-link_them() {
-    for dot_source in $(dotsources); do
-        target=$(symlink_names ${dot_source})
-        for symlink in ${target}; do
-            ln -s ${cwd}/${dot_source} ${symlink}
-        done
-    done
-}
+sh ${cmd_file} && rm ${cmd_file}
 
-dotlink() {
-    $(dotdelete)
-    $(ensure_directories)
-    $(link_them)
-}
-
-usage() {
-    echo "Usage: 'sh $0 <install|backup>'"
-    echo "Consider including 'curl -L get.yeoman.io | sh' to this setup"
-    exit 1
-}
-
-[[ $# != 1 ]] && usage
-
-case $1 in
-    install)
-        $(dotlink) ;;
-    backup)
-        $(dotbackup) ;;
-    *)
-        echo $(usage) ;;
-esac
+echo "Done"
